### PR TITLE
#17 add loading animation to the frontend + minor fixes

### PR DESCRIPTION
**Pull request by andrewtavis**
Addresses the need for a loading animation while there's still no response as discussed in #17 😊 Along with that, I'm also including few minor adjustments to the texts and spacing as discussed in [this comment here](https://github.com/rti/gbnc/issues/17#issuecomment-1919049866).

Happy testing!

### CODE REVIEW

**Comment by andrewtavis** [comment]
Current animation is:

https://github.com/rti/gbnc/assets/24387426/47724ff7-0dd7-4058-9bb7-3873e1f40532

Feel free to adjust as needed or let me know if something should change.

**Review by exowanderer — APPROVED** [review]
I am not able to understand the code itself. But I like the result as seen in the short video. I approve here the topic and result. But cannot comment on the code itself.

**Comment by rti** [comment]
Thanks a lot for your work!

**Comment by andrewtavis** [comment]
Very welcome! Hope it makes the loading times a bit more enjoyable 😊

**Pull request merged**
